apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-application
    namespace: whanos
    labels:
        app: my-application
spec:
    replicas: 2
    selector:
        matchLabels:
            app: my-application
    template:
        metadata:
            labels:
                app: my-application
        spec:
            containers:
                - name: my-application-container
                  image: "<IMAGE_NAME>"
                  ports:
                      - containerPort: 3000
                      - containerPort: 5000
                  resources:
                      requests:
                          memory: "64Mi"
                      limits:
                          memory: "256Mi"
            imagePullSecrets:
                - name: whano
---
apiVersion: v1
kind: Service
metadata:
    name: my-application-service
    namespace: whanos
spec:
    type: LoadBalancer
    ports:
        - name: http
          port: 80
          targetPort: 3000
        - name: management
          port: 8081
          targetPort: 5000
    selector:
        app: my-application
