apiVersion: apps/v1
kind: Deployment
deployment:
    replicas: 2
    resources:
        limits:
            memory: "256M"
        requests:
            memory: "64M"
    ports:
        - 3000
        - 5000
