apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-application
    labels:
        app: my-application
spec:
    replicas: 2 # Modifiable avec la propriété replicas
    selector:
        matchLabels:
            app: my-application
    template:
        metadata:
            labels:
                app: my-application
        spec:
            containers:
                - name: my-application-container
                  image: "<IMAGE_NAME>" # Remplacé dynamiquement par votre script
                  ports:
                      - containerPort: 3000 # Exemple, configurable via ports dans whanos.yml
                      - containerPort: 5000
                  resources: # Spécifications des ressources si disponibles dans whanos.yml
                      requests:
                          memory: "64Mi"
                      limits:
                          memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
    name: my-application-service
spec:
    type: LoadBalancer # Pour exposer l'application à l'extérieur
    ports:
        - name: http # Nom unique pour ce port
          port: 80
          targetPort: 3000 # Redirige vers un des ports du container
        - name: management # Nom unique pour ce port
          port: 8080
          targetPort: 5000
    selector:
        app: my-application
